// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg7xb388-JjSqzLu98PLPe7Q1QiAJzEkg',
    appId: '1:407438723569:web:4525e3f62905f040b91c50',
    messagingSenderId: '407438723569',
    projectId: 'fir-testing-7f2d0',
    authDomain: 'fir-testing-7f2d0.firebaseapp.com',
    storageBucket: 'fir-testing-7f2d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3sBl6dP5SxpClP9gvFQZbzIo5OO1MWL4',
    appId: '1:407438723569:android:8e27b1f5501c0120b91c50',
    messagingSenderId: '407438723569',
    projectId: 'fir-testing-7f2d0',
    storageBucket: 'fir-testing-7f2d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUJeoukZp6Cqj9-aUfpejMHNX79aaReGo',
    appId: '1:407438723569:ios:3d31dab786057c51b91c50',
    messagingSenderId: '407438723569',
    projectId: 'fir-testing-7f2d0',
    storageBucket: 'fir-testing-7f2d0.appspot.com',
    iosBundleId: 'com.example.firebaseTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUJeoukZp6Cqj9-aUfpejMHNX79aaReGo',
    appId: '1:407438723569:ios:b1145bca1264dd08b91c50',
    messagingSenderId: '407438723569',
    projectId: 'fir-testing-7f2d0',
    storageBucket: 'fir-testing-7f2d0.appspot.com',
    iosBundleId: 'com.example.firebaseTesting.RunnerTests',
  );
}
